version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '8888:8888'
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=8888

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_FILE_BASE_URL=http://backend:8888/
      - VITE_BACKEND_SERVER=http://backend:8888/
