version: '3.8'

services:
  nextjs-app:
    build: 
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/projectdb}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB:-projectdb}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: